
name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: 🧾 Klona källkod
      uses: actions/checkout@v3

    - name: ⚙️ Installera beroenden
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel
        pip install --user buildozer cython

    - name: 🏗️ Bygg APK med Buildozer
      run: |
        export PATH=$HOME/.local/bin:$PATH
        buildozer android debug

    - name: 📦 Ladda upp APK som artifact
      uses: actions/upload-artifact@v4
      with:
        name: flashcard-app-debug
        path: bin/*.apk
